[server]
headless = true
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#080D1A"
secondaryBackgroundColor = "#0F172A"
textColor = "#E2E8F0"
